apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch-master
  name: elasticsearch-master
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: elasticsearch-master
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch-master
    spec:
      containers:
        - env:
            - name: DISCOVERY_SERVICE
              value: elasticsearch
            - name: NODE_MASTER
              value: "true"
            - name: discovery.seed_hosts
              value: elasticsearch
            - name: cluster.initial_master_nodes
              value: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
          imagePullPolicy: IfNotPresent
          name: elasticsearch-master
          ports:
            - containerPort: 9200
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          image: busybox:1.27.2
          imagePullPolicy: IfNotPresent
          name: init-sysctl
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: monitoring
spec:
  ports:
    - nodePort: 31031
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    app: elasticsearch-master
  sessionAffinity: None
  type: NodePort