package com.mvillafuertem.services.authentication.management.configuration.application

import com.mvillafuertem.services.authentication.management.application.service.AuthenticateUser
import com.mvillafuertem.services.authentication.management.configuration.infrastructure.InfrastructureConfiguration

final class ApplicationConfiguration(infrastructureConfiguration: InfrastructureConfiguration) {

  val userAuthenticator = new AuthenticateUser(infrastructureConfiguration.authenticationManagementRepository)
}
